<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- Specify some standard inertial calculations https://en.wikipedia.org/wiki/List_of_moments_of_inertia -->
    <!-- These make use of xacro's mathematical functionality -->




    <!-- ################### inertia macros  ############################-->

    <xacro:macro name="inertial_sphere" params="mass radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(2/5) * mass * (radius*radius)}" ixy="0.0" ixz="0.0"
                    iyy="${(2/5) * mass * (radius*radius)}" iyz="0.0"
                    izz="${(2/5) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>  

    <xacro:macro name="inertial_box" params="mass x y z *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (y*y+z*z)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (x*x+z*z)}" iyz="0.0"
                    izz="${(1/12) * mass * (x*x+y*y)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="inertial_cylinder" params="mass length radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
                    izz="${(1/2) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>

    <!-- ###################################################################################### -->






    <!-- These make use of xacro's mathematical functionality -->
    
    <xacro:macro name="insert_drive_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <xacro:if value="${rviz_visual}">
                    <mesh filename="package://obot_description/meshes/wheel.stl"/>
                </xacro:if>
                <xacro:if value="${gazebo_visual}">
                    <mesh filename="$(find obot_description)/meshes/wheel.stl"/>
                </xacro:if>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.05" length="0.02"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="0.8" length="0.02" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </xacro:macro>




    <xacro:macro name="insert_caster_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <xacro:if value="${rviz_visual}">
                    <mesh filename="package://obot_description/meshes/caster_wheel.stl"/>
                </xacro:if>
                <xacro:if value="${gazebo_visual}">
                    <mesh filename="$(find obot_description)/meshes/caster_wheel.stl"/>
                </xacro:if>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.019" length="0.02"/>
            </geometry>
        </collision>
        
        <xacro:inertial_cylinder mass="0.4" length="0.02" radius="0.019">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </xacro:macro>



    <xacro:macro name="insert_caster_holder_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <xacro:if value="${rviz_visual}">
                    <mesh filename="package://obot_description/meshes/caster_holder.stl"/>
                </xacro:if>
                <xacro:if value="${gazebo_visual}">
                    <mesh filename="$(find obot_description)/meshes/caster_holder.stl"/>
                </xacro:if>
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <xacro:if value="${rviz_visual}">
                    <mesh filename="package://obot_description/meshes/caster_holder.stl"/>
                </xacro:if>
                <xacro:if value="${gazebo_visual}">
                    <mesh filename="$(find obot_description)/meshes/caster_holder.stl"/>
                </xacro:if>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="0.2" length="0.04" radius="0.02">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </xacro:macro>


    <xacro:macro name="insert_support" params="x y">
        <visual>
            <origin xyz="${x} ${y} ${slab_height/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.01" length="${slab_height}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="${x} ${y} ${slab_height/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.01" length="${slab_height}"/>
            </geometry>
        </collision>
    </xacro:macro>









    <!-- <visual>
            <origin xyz="0.04 -0.14 ${slab_height/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.01" length="${slab_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <visual>
            <origin xyz="0.04 0.14 ${slab_height/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.01" length="${slab_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <visual>
            <origin xyz="-0.12 0.08 ${slab_height/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.01" length="${slab_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <visual>
            <origin xyz="-0.12 -0.08 ${slab_height/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.01" length="${slab_height}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="0.04 -0.14 ${slab_height/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.01" length="${slab_height}"/>
            </geometry>
        </collision>
        <collision>
            <origin xyz="0.04 0.14 ${slab_height/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.01" length="${slab_height}"/>
            </geometry>
        </collision>
        <collision>
            <origin xyz="-0.12 0.08 ${slab_height/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.01" length="${slab_height}"/>
            </geometry>
        </collision>
        <collision>
            <origin xyz="-0.12 -0.08 ${slab_height/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.01" length="${slab_height}"/>
            </geometry>
        </collision> -->

    


</robot>